#!/usr/bin/env python3
"""Fail-closed Phase 7 promotion and evidence-ledger primitives.

The module deliberately has no subprocess, socket, CUDA, model, or package
download integration.  It validates prospective plans and evidence generated by
an independently authorized executor.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import copy
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence


STAGES = ("M0", "M1", "M2", "M3", "M4")
IDENTITY_FIELDS = (
    "collector_hash",
    "adapter_hash",
    "schema_hash",
    "correlation_hash",
    "alignment_hash",
    "routing_hook_hash",
    "generation_identity_hash",
)
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")
SESSION_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{7,127}$")


class ContractError(ValueError):
    """Raised when a Phase 7 contract would otherwise fail open."""


def _reject_duplicate_keys(pairs: Sequence[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ContractError(f"duplicate JSON key: {key}")
        result[key] = value
    return result


def load_strict_json(path: Path) -> Any:
    try:
        return json.loads(
            path.read_text(encoding="utf-8"),
            object_pairs_hook=_reject_duplicate_keys,
        )
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        raise ContractError(f"cannot load strict JSON {path}: {exc}") from exc


def canonical_bytes(value: Any) -> bytes:
    try:
        return json.dumps(
            value,
            ensure_ascii=False,
            allow_nan=False,
            sort_keys=True,
            separators=(",", ":"),
        ).encode("utf-8")
    except (TypeError, ValueError) as exc:
        raise ContractError(f"value is not canonical JSON: {exc}") from exc


def semantic_sha256(value: Any) -> str:
    return hashlib.sha256(canonical_bytes(value)).hexdigest()


def file_sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _require_exact_keys(
    value: Mapping[str, Any], required: set[str], optional: set[str], label: str
) -> None:
    missing = required - set(value)
    extra = set(value) - required - optional
    if missing or extra:
        raise ContractError(
            f"{label} key mismatch; missing={sorted(missing)}, extra={sorted(extra)}"
        )


def _require_sha(value: Any, label: str) -> str:
    if not isinstance(value, str) or not SHA256_RE.fullmatch(value):
        raise ContractError(f"{label} must be a lowercase SHA-256")
    return value


def variant_hash(identity: Mapping[str, Any]) -> str:
    _require_exact_keys(identity, set(IDENTITY_FIELDS), set(), "variant_identity")
    for field in IDENTITY_FIELDS:
        _require_sha(identity[field], f"variant_identity.{field}")
    return semantic_sha256(dict(identity))


def _distinct_strings(value: Any, expected_count: int, label: str) -> list[str]:
    if (
        not isinstance(value, list)
        or len(value) != expected_count
        or any(not isinstance(item, str) or not item for item in value)
        or len(set(value)) != expected_count
    ):
        raise ContractError(f"{label} must contain {expected_count} distinct strings")
    return value


def _validate_matrix(promotions: Mapping[str, Any]) -> None:
    _require_exact_keys(promotions, set(STAGES), set(), "promotions")

    m0 = promotions["M0"]
    _require_exact_keys(m0, {"unit_ids"}, set(), "promotions.M0")
    if not isinstance(m0["unit_ids"], list) or not m0["unit_ids"]:
        raise ContractError("M0 requires at least one qualification unit")
    if len(set(m0["unit_ids"])) != len(m0["unit_ids"]) or any(
        not isinstance(item, str) or not item for item in m0["unit_ids"]
    ):
        raise ContractError("M0 unit_ids must be distinct non-empty strings")

    m1 = promotions["M1"]
    _require_exact_keys(m1, {"sample_ids"}, set(), "promotions.M1")
    _distinct_strings(m1["sample_ids"], 8, "M1 sample_ids")

    m2 = promotions["M2"]
    _require_exact_keys(
        m2, {"sample_ids", "repetitions", "passes", "cell_count"}, set(), "promotions.M2"
    )
    _distinct_strings(m2["sample_ids"], 48, "M2 sample_ids")
    if m2["repetitions"] != 3 or m2["passes"] != ["P0", "P2"]:
        raise ContractError("M2 must be 48 samples x 3 repetitions x P0/P2")
    expected_m2 = len(m2["sample_ids"]) * m2["repetitions"] * len(m2["passes"])
    if m2["cell_count"] != expected_m2 or expected_m2 != 288:
        raise ContractError("M2 exact cell count must be 288")

    m3 = promotions["M3"]
    _require_exact_keys(
        m3, {"sample_ids", "repetitions", "passes", "cell_count"}, set(), "promotions.M3"
    )
    _distinct_strings(m3["sample_ids"], 12, "M3 sample_ids")
    if m3["repetitions"] != 3 or m3["passes"] != ["P1", "P3", "P4"]:
        raise ContractError("M3 must be 12 samples x 3 repetitions x P1/P3/P4")
    expected_m3 = len(m3["sample_ids"]) * m3["repetitions"] * len(m3["passes"])
    if m3["cell_count"] != expected_m3 or expected_m3 != 108:
        raise ContractError("M3 exact cell count must be 108")

    m4 = promotions["M4"]
    _require_exact_keys(
        m4,
        {"scenario_ids", "repetitions", "modes", "session_count"},
        set(),
        "promotions.M4",
    )
    _distinct_strings(m4["scenario_ids"], 6, "M4 scenario_ids")
    if m4["repetitions"] != 3 or m4["modes"] != ["CLEAN", "INSTRUMENTED"]:
        raise ContractError(
            "M4 must be 6 scenarios x 3 repetitions x CLEAN/INSTRUMENTED"
        )
    expected_m4 = (
        len(m4["scenario_ids"]) * m4["repetitions"] * len(m4["modes"])
    )
    if m4["session_count"] != expected_m4 or expected_m4 != 36:
        raise ContractError("M4 exact session count must be 36")


def validate_plan(plan: Mapping[str, Any]) -> dict[str, Any]:
    _require_exact_keys(
        plan,
        {
            "schema_version",
            "session_id",
            "fresh_session",
            "resume_session_id",
            "retry_failed",
            "copy_prior_evidence",
            "execution_profile",
            "variant_identity",
            "variant_hash",
            "v0",
            "promotions",
        },
        set(),
        "plan",
    )
    if plan["schema_version"] != "moe-simulator-phase7-plan-v1":
        raise ContractError("unsupported Phase 7 plan schema_version")
    if not isinstance(plan["session_id"], str) or not SESSION_RE.fullmatch(
        plan["session_id"]
    ):
        raise ContractError("invalid session_id")
    if plan["fresh_session"] is not True:
        raise ContractError("fresh_session must be true")
    if plan["resume_session_id"] is not None:
        raise ContractError("old-session resume is forbidden")
    if plan["retry_failed"] is not False:
        raise ContractError("retry_failed is forbidden")
    if plan["copy_prior_evidence"] is not False:
        raise ContractError("copying prior evidence is forbidden")
    if plan["execution_profile"] != "CPU_MOCK_DRY_RUN":
        raise ContractError("local preflight accepts CPU_MOCK_DRY_RUN only")

    calculated_variant_hash = variant_hash(plan["variant_identity"])
    if plan["variant_hash"] != calculated_variant_hash:
        raise ContractError("variant_hash does not match variant_identity")

    if plan["v0"] != {
        "execution_role": "OFFLINE_VALIDATION",
        "gpu_execution": False,
        "runtime_pass": False,
    }:
        raise ContractError("V0 must be offline validation with no GPU/runtime pass")

    if not isinstance(plan["promotions"], Mapping):
        raise ContractError("promotions must be an object")
    _validate_matrix(plan["promotions"])
    return {
        "plan_hash": semantic_sha256(plan),
        "variant_hash": calculated_variant_hash,
        "session_id": plan["session_id"],
    }


def validate_approval(
    approval: Mapping[str, Any],
    *,
    plan: Mapping[str, Any],
    stage: str,
    used_approval_ids: Iterable[str] = (),
    used_token_hashes: Iterable[str] = (),
) -> dict[str, Any]:
    if stage not in STAGES:
        raise ContractError(f"invalid stage: {stage}")
    plan_result = validate_plan(plan)
    _require_exact_keys(
        approval,
        {
            "schema_version",
            "approval_id",
            "stage",
            "session_id",
            "variant_hash",
            "plan_hash",
            "scope",
            "decision",
            "token_sha256",
        },
        set(),
        "approval",
    )
    if approval["schema_version"] != "moe-simulator-phase7-owner-approval-v1":
        raise ContractError("unsupported owner approval schema_version")
    expected = {
        "stage": stage,
        "session_id": plan_result["session_id"],
        "variant_hash": plan_result["variant_hash"],
        "plan_hash": plan_result["plan_hash"],
        "scope": f"PHASE7_{stage}_CPU_MOCK_DRY_RUN",
        "decision": "APPROVE",
    }
    for field, expected_value in expected.items():
        if approval[field] != expected_value:
            raise ContractError(f"approval {field} is not bound to this request")
    if not isinstance(approval["approval_id"], str) or not approval["approval_id"]:
        raise ContractError("approval_id must be a non-empty string")
    token_hash = _require_sha(approval["token_sha256"], "approval.token_sha256")
    if approval["approval_id"] in set(used_approval_ids):
        raise ContractError("approval_id reuse is forbidden")
    if token_hash in set(used_token_hashes):
        raise ContractError("approval token hash reuse is forbidden")
    return {
        "approval_hash": semantic_sha256(approval),
        "approval_id": approval["approval_id"],
        "token_sha256": token_hash,
    }


def validate_state(state: Mapping[str, Any], plan: Mapping[str, Any]) -> None:
    _require_exact_keys(
        state,
        {
            "schema_version",
            "session_id",
            "plan_hash",
            "variant_hash",
            "status",
            "completed_stages",
            "approvals",
            "evidence_ledgers",
            "invalidations",
            "evidence_class",
            "claim_boundary",
            "gpu_authority",
        },
        set(),
        "state",
    )
    if state["schema_version"] != "moe-simulator-phase7-state-v1":
        raise ContractError("unsupported state schema")
    plan_result = validate_plan(plan)
    for field in ("session_id", "plan_hash", "variant_hash"):
        if state[field] != plan_result[field]:
            raise ContractError(f"state {field} does not match plan")
    completed = state["completed_stages"]
    if not isinstance(completed, list) or any(stage not in STAGES for stage in completed):
        raise ContractError("completed_stages is invalid")
    if completed != list(STAGES[: len(completed)]):
        raise ContractError("completed_stages must be a contiguous M0-M4 prefix")
    if state["status"] not in {
        "FRESH_CPU_MOCK",
        "ACTIVE_CPU_MOCK",
        "COMPLETE_CPU_MOCK_FRAMEWORK_ONLY",
        "FAILED_CPU_MOCK",
        "INVALIDATED_VARIANT_CHANGE",
    }:
        raise ContractError("invalid state status")
    if (
        state["status"] == "COMPLETE_CPU_MOCK_FRAMEWORK_ONLY"
        and completed != list(STAGES)
    ):
        raise ContractError("CPU mock framework completion requires all M0-M4 stages")
    if state["evidence_class"] != "CPU_MOCK":
        raise ContractError("local Phase 7 state evidence_class must be CPU_MOCK")
    if state["claim_boundary"] != "FRAMEWORK_VALIDATION_ONLY":
        raise ContractError("local Phase 7 state cannot claim formal promotion")
    if state["gpu_authority"] != "NONE":
        raise ContractError("local Phase 7 state has no GPU authority")
    approvals = state["approvals"]
    ledgers = state["evidence_ledgers"]
    if (
        not isinstance(approvals, Mapping)
        or not isinstance(ledgers, Mapping)
        or set(approvals) != set(completed)
        or set(ledgers) != set(completed)
    ):
        raise ContractError("each completed stage requires approval and evidence ledger")
    approval_ids: set[str] = set()
    tokens: set[str] = set()
    for completed_stage in completed:
        binding = approvals[completed_stage]
        if not isinstance(binding, Mapping):
            raise ContractError("approval state binding must be an object")
        _require_exact_keys(
            binding,
            {"approval_id", "token_sha256", "approval_hash"},
            set(),
            f"state approval {completed_stage}",
        )
        approval_id = binding.get("approval_id")
        token = binding.get("token_sha256")
        _require_sha(token, f"state approval {completed_stage} token")
        _require_sha(
            binding.get("approval_hash"),
            f"state approval {completed_stage} approval_hash",
        )
        if not isinstance(approval_id, str) or not approval_id:
            raise ContractError("state approval_id is invalid")
        if approval_id in approval_ids or token in tokens:
            raise ContractError("stage approvals must use independent IDs and tokens")
        approval_ids.add(approval_id)
        tokens.add(token)
        _require_sha(
            ledgers[completed_stage],
            f"state evidence ledger {completed_stage}",
        )


def next_stage(state: Mapping[str, Any], plan: Mapping[str, Any]) -> str | None:
    validate_state(state, plan)
    if state["status"] in {"FAILED_CPU_MOCK", "INVALIDATED_VARIANT_CHANGE"}:
        raise ContractError("failed or invalidated sessions cannot resume")
    count = len(state["completed_stages"])
    return None if count == len(STAGES) else STAGES[count]


def new_state(plan: Mapping[str, Any], existing_session_ids: Iterable[str]) -> dict[str, Any]:
    result = validate_plan(plan)
    if result["session_id"] in set(existing_session_ids):
        raise ContractError("session_id already exists; old-session resume is forbidden")
    return {
        "schema_version": "moe-simulator-phase7-state-v1",
        "session_id": result["session_id"],
        "plan_hash": result["plan_hash"],
        "variant_hash": result["variant_hash"],
        "status": "FRESH_CPU_MOCK",
        "completed_stages": [],
        "approvals": {},
        "evidence_ledgers": {},
        "invalidations": [],
        "evidence_class": "CPU_MOCK",
        "claim_boundary": "FRAMEWORK_VALIDATION_ONLY",
        "gpu_authority": "NONE",
    }


def assess_variant_change(
    state: Mapping[str, Any],
    plan: Mapping[str, Any],
    proposed_identity: Mapping[str, Any],
) -> dict[str, Any]:
    validate_state(state, plan)
    proposed_hash = variant_hash(proposed_identity)
    changed = [
        field
        for field in IDENTITY_FIELDS
        if proposed_identity[field] != plan["variant_identity"][field]
    ]
    invalidated = (
        [stage for stage in state["completed_stages"] if stage in STAGES[1:]]
        if changed
        else []
    )
    return {
        "changed_fields": changed,
        "old_variant_hash": state["variant_hash"],
        "new_variant_hash": proposed_hash,
        "invalidated_stages": invalidated,
        "m1_evidence_valid": not changed,
        "fresh_session_required": bool(changed),
        "promotion_allowed": not changed,
    }


def invalidate_state_for_variant_change(
    state: Mapping[str, Any],
    plan: Mapping[str, Any],
    proposed_identity: Mapping[str, Any],
) -> dict[str, Any]:
    """Invalidate an old CPU-mock session without deleting historical evidence.

    A changed identity cannot be installed into the old session.  The returned
    terminal state records which prior stages are no longer promotable and binds
    the prospective variant hash.  Work must restart in a separately registered
    fresh session.
    """

    report = assess_variant_change(state, plan, proposed_identity)
    if not report["changed_fields"]:
        raise ContractError("identity is unchanged; invalidation is not applicable")
    invalidated = copy.deepcopy(dict(state))
    invalidated["status"] = "INVALIDATED_VARIANT_CHANGE"
    invalidated["invalidations"].append(
        {
            "reason": "RUNTIME_VARIANT_IDENTITY_CHANGED",
            "changed_fields": report["changed_fields"],
            "invalidated_stages": report["invalidated_stages"],
            "old_variant_hash": report["old_variant_hash"],
            "proposed_variant_hash": report["new_variant_hash"],
            "required_action": "CREATE_FRESH_SESSION_AND_RESTART_AT_M0_THEN_M1",
        }
    )
    validate_state(invalidated, plan)
    return invalidated


def _safe_artifact_path(root: Path, relative: str) -> Path:
    if not isinstance(relative, str) or not relative:
        raise ContractError("artifact path must be a non-empty string")
    candidate_rel = Path(relative)
    if candidate_rel.is_absolute() or ".." in candidate_rel.parts:
        raise ContractError(f"artifact path escapes evidence root: {relative}")
    root_real = root.resolve(strict=True)
    candidate = root_real.joinpath(candidate_rel)
    if candidate.is_symlink():
        raise ContractError(f"symlink artifacts are forbidden: {relative}")
    candidate_real = candidate.resolve(strict=True)
    if candidate_real == root_real or root_real not in candidate_real.parents:
        raise ContractError(f"artifact path escapes evidence root: {relative}")
    if not candidate_real.is_file():
        raise ContractError(f"artifact is not a regular file: {relative}")
    return candidate_real


def build_artifact_ledger(
    root: Path, relative_paths: Sequence[str], *, stage: str, session_id: str
) -> dict[str, Any]:
    if stage not in STAGES and stage != "V0":
        raise ContractError("ledger stage must be M0-M4 or V0")
    if not SESSION_RE.fullmatch(session_id):
        raise ContractError("invalid ledger session_id")
    if not relative_paths or len(relative_paths) != len(set(relative_paths)):
        raise ContractError("artifact paths must be non-empty and unique")
    members = []
    for relative in sorted(relative_paths):
        artifact = _safe_artifact_path(root, relative)
        members.append(
            {
                "path": relative,
                "size_bytes": artifact.stat().st_size,
                "sha256": file_sha256(artifact),
            }
        )
    ledger = {
        "schema_version": "moe-simulator-phase7-artifact-ledger-v1",
        "session_id": session_id,
        "stage": stage,
        "member_count": len(members),
        "members": members,
    }
    ledger["ledger_sha256"] = semantic_sha256(ledger)
    return ledger


def verify_artifact_ledger(root: Path, ledger: Mapping[str, Any]) -> None:
    _require_exact_keys(
        ledger,
        {
            "schema_version",
            "session_id",
            "stage",
            "member_count",
            "members",
            "ledger_sha256",
        },
        set(),
        "artifact ledger",
    )
    if ledger["schema_version"] != "moe-simulator-phase7-artifact-ledger-v1":
        raise ContractError("unsupported artifact ledger schema")
    without_hash = dict(ledger)
    claimed_hash = without_hash.pop("ledger_sha256")
    if claimed_hash != semantic_sha256(without_hash):
        raise ContractError("artifact ledger semantic hash mismatch")
    if ledger["member_count"] != len(ledger["members"]) or not ledger["members"]:
        raise ContractError("artifact ledger member_count mismatch")
    paths: list[str] = []
    for member in ledger["members"]:
        _require_exact_keys(
            member, {"path", "size_bytes", "sha256"}, set(), "artifact ledger member"
        )
        path = _safe_artifact_path(root, member["path"])
        if path.stat().st_size != member["size_bytes"]:
            raise ContractError(f"artifact size mismatch: {member['path']}")
        if file_sha256(path) != member["sha256"]:
            raise ContractError(f"artifact checksum mismatch: {member['path']}")
        paths.append(member["path"])
    if paths != sorted(paths) or len(paths) != len(set(paths)):
        raise ContractError("artifact ledger members must be sorted and unique")


def write_json_atomic(path: Path, value: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n"
    temporary = path.with_name(f".{path.name}.{os.getpid()}.tmp")
    try:
        with temporary.open("x", encoding="utf-8") as stream:
            stream.write(payload)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


@dataclass(frozen=True)
class PreflightResult:
    stage: str
    session_id: str
    plan_hash: str
    variant_hash: str
    approval_hash: str
    action: str = "PREFLIGHT_ONLY"
    execution_profile: str = "CPU_MOCK_DRY_RUN"
    execution_performed: bool = False
    gpu_authority: str = "NONE"

    def as_dict(self) -> dict[str, Any]:
        return {
            "schema_version": "moe-simulator-phase7-preflight-result-v1",
            "stage": self.stage,
            "session_id": self.session_id,
            "plan_hash": self.plan_hash,
            "variant_hash": self.variant_hash,
            "approval_hash": self.approval_hash,
            "action": self.action,
            "execution_profile": self.execution_profile,
            "execution_performed": self.execution_performed,
            "gpu_authority": self.gpu_authority,
            "network_used": False,
            "model_downloaded": False,
            "formal_profiling_performed": False,
        }


def preflight(
    plan: Mapping[str, Any],
    approval: Mapping[str, Any],
    state: Mapping[str, Any],
    *,
    stage: str,
) -> PreflightResult:
    validate_state(state, plan)
    expected_stage = next_stage(state, plan)
    if expected_stage != stage:
        raise ContractError(f"expected next stage {expected_stage}, got {stage}")
    used_ids = [entry["approval_id"] for entry in state["approvals"].values()]
    used_tokens = [entry["token_sha256"] for entry in state["approvals"].values()]
    approval_result = validate_approval(
        approval,
        plan=plan,
        stage=stage,
        used_approval_ids=used_ids,
        used_token_hashes=used_tokens,
    )
    plan_result = validate_plan(plan)
    return PreflightResult(
        stage=stage,
        session_id=plan_result["session_id"],
        plan_hash=plan_result["plan_hash"],
        variant_hash=plan_result["variant_hash"],
        approval_hash=approval_result["approval_hash"],
    )


def promote_cpu_mock_stage(
    plan: Mapping[str, Any],
    approval: Mapping[str, Any],
    state: Mapping[str, Any],
    *,
    stage: str,
    evidence_root: Path,
    artifact_ledger: Mapping[str, Any],
) -> dict[str, Any]:
    """Advance one CPU-mock framework stage after full approval/evidence checks.

    This transition never authorizes or records a formal hardware promotion.
    """

    result = preflight(plan, approval, state, stage=stage)
    verify_artifact_ledger(evidence_root, artifact_ledger)
    if artifact_ledger["stage"] != stage:
        raise ContractError("artifact ledger stage does not match promotion stage")
    if artifact_ledger["session_id"] != result.session_id:
        raise ContractError("artifact ledger session does not match promotion session")

    approval_result = validate_approval(
        approval,
        plan=plan,
        stage=stage,
        used_approval_ids=[
            entry["approval_id"] for entry in state["approvals"].values()
        ],
        used_token_hashes=[
            entry["token_sha256"] for entry in state["approvals"].values()
        ],
    )
    promoted = copy.deepcopy(dict(state))
    promoted["completed_stages"].append(stage)
    promoted["approvals"][stage] = {
        "approval_id": approval_result["approval_id"],
        "token_sha256": approval_result["token_sha256"],
        "approval_hash": approval_result["approval_hash"],
    }
    promoted["evidence_ledgers"][stage] = artifact_ledger["ledger_sha256"]
    promoted["status"] = (
        "COMPLETE_CPU_MOCK_FRAMEWORK_ONLY"
        if promoted["completed_stages"] == list(STAGES)
        else "ACTIVE_CPU_MOCK"
    )
    validate_state(promoted, plan)
    return promoted
