#!/usr/bin/env python3
"""Promote OFF-W3 representative paired-profiler evidence."""
from __future__ import annotations
import argparse, json
from pathlib import Path
from promote_combined_master_swap_k1_v5 import aggregate_hash,append_unique,evidence_file_hashes,legally_closed,now_utc,read_json,sha256_file,write_json

CONTRACT_SHA="3976012547c4678853e690ae38f6392469dd0d08dd0ee7538824dc8819a6ebaa"
ROUTING_SHA="26546e41d43eb414e24d81a876b7c0d583358bfbe83b6191d8f851bf0c461fcf"

def once(records,record):
    if not any(x.get('attempt_id')==record['attempt_id'] for x in records): records.append(record)

def main():
    p=argparse.ArgumentParser();p.add_argument('--master-root',type=Path,required=True);p.add_argument('--local-attempt-root',type=Path,required=True);p.add_argument('--remote-attempt-root',required=True);p.add_argument('--expected-aggregate-sha256',required=True);p.add_argument('--remote-suite-manifest-sha256',required=True);a=p.parse_args();s=a.local_attempt_root
    if sha256_file(s/'SUITE_SHA256SUMS')!=a.remote_suite_manifest_sha256: raise SystemExit('OFF-W3 suite manifest mismatch')
    raw=aggregate_hash(evidence_file_hashes(s))
    if raw!=a.expected_aggregate_sha256: raise SystemExit(f'OFF-W3 aggregate mismatch: {raw}')
    audit=read_json(s/'off_w3_suite_audit.json'); tech=(s/'audit.v1.technical_failure.stderr.log').read_text(errors='replace')
    if audit.get('status')!='PASS' or audit.get('pair_output_routing_equivalence')!='PASS' or sha256_file(s/'off_w3_contract.json')!=CONTRACT_SHA or 'UnboundLocalError' not in tech: raise SystemExit('OFF-W3 suite/audit-repair gate failed')
    pts={x['point_id']:x for x in audit['points']}
    if set(pts)!={'DISABLED','UVA-HELDOUT'} or pts['DISABLED']['actual_offloaded_bytes']!=0 or pts['UVA-HELDOUT']['actual_offloaded_bytes']!=4697620480: raise SystemExit('OFF-W3 point identity/bytes gate failed')
    for x in pts.values():
        prof=x['profiler']
        if x['configuration']!='PASS' or x['correctness']!='PASS' or x['profiler_gate']!='PASS' or x['routing_sha256']!=ROUTING_SHA or prof.get('validation_status')!='PASS' or prof.get('kernel_event_count',0)<=0 or prof.get('model_kernel_event_count',0)<=0 or prof.get('prefill_marker_count',0)<=0 or prof.get('decode_marker_count',0)<=0 or prof.get('attention_marker_count',0)<=0 or prof.get('moe_marker_count',0)<=0 or prof.get('correlation_event_count',0)<=0: raise SystemExit(f"OFF-W3 profiler gate failed: {x['point_id']}")
    point_dirs={k:next((s/'points'/k/'runner_runs').iterdir()) for k in pts}; durations={k:read_json(d/'result.json')['wall_duration_ns'] for k,d in point_dirs.items()}
    root=a.master_root;lp=root/'master_execution_ledger.json';ledger=read_json(lp);prior=sha256_file(lp);rows=ledger['rows'];row=next(x for x in rows if x['master_row_id']=='OFF-W3');tid='MR11-OFF-W3-OFF-W3-V1-MASTER-PROMOTION'
    for key,value in [('attempt_ids','OFF-W3-V1-MASTER'),('remote_raw_paths',a.remote_attempt_root),('local_raw_paths',str(s)),('source_raw_sha256',raw)]:
        if value not in row.setdefault(key,[]): row[key].append(value)
    append_unique(row.setdefault('manifest_sha256',[]),[a.remote_suite_manifest_sha256,sha256_file(s/'off_w3_suite_audit.json'),CONTRACT_SHA,sha256_file(s/'audit.v1.technical_failure.stderr.log')])
    row.setdefault('repair_lineage',[]).append({'failed_phase':'suite_audit_v1','failure_class':'TECHNICAL_UNBOUND_LOCAL_AFTER_BOTH_GPU_POINTS_PASS','repair':'Move runner-directory assignment outside the conditional suite in audit-only code.','replacement_phase':'suite_audit_v2','gpu_points_rerun':False,'scientific_contract_changed':False})
    row.update({'execution_state':'EXECUTION_COMPLETE','raw_state':'COMPLETE','backup_state':'VERIFIED','review_state':'REVIEW_WITH_LIMITATION','validation_state':'VALIDATION_PASS','adoption_state':'ADOPTED','blocker_or_failure':None,'claims_supported':append_unique(list(row.get('claims_supported',[])),['A frozen 4096-to-128 disabled/UVA paired worker-profiler run preserved exact output tokens and routed-expert array with 4.375 GiB actually UVA-offloaded.','Both variants produced parseable prefill/decode-correlated traces with 48,096 GPU kernels, 40,160 model kernels, H2D/D2H records, attention and MoE markers.','The single observed profiled request durations were 43.203610984 s disabled and 76.584818259 s UVA; retained as diagnostic observations only.']),'claims_forbidden':append_unique(list(row.get('claims_forbidden',[])),['Formal latency slowdown/speedup, bandwidth, tail, energy or statistical claims from one profiled pair.','Interpreting identical explicit memcpy counters as absence of UVA host access; UVA uses direct host-address access.','Dynamic expert residency conclusions from generic selective UVA weight offload.']),'contamination_flags':append_unique(list(row.get('contamination_flags',[])),['OFF_W3_AUDIT_V1_TECHNICAL_FAILURE_PRESERVED_NO_GPU_RERUN','OFF_W3_ONE_PROFILED_PAIR_NOT_FORMAL_PERFORMANCE']),'next_action':'Return to the core-required MR10 queue and freeze OFF-E-PR0 compute-integrated replay before dispatch.','last_transition_record':tid})
    trans={'transition_id':tid,'timestamp_utc':now_utc(),'changed_rows':['OFF-W3'],'reason':'Promote representative paired-profiler correctness/kernel/copy/memory evidence with audit-only repair lineage and strict claim limits.','prior_ledger_sha256':prior,'attempt_id':'OFF-W3-V1-MASTER','raw_file_set_sha256':raw,'wall_duration_ns':durations,'remote_local_hashes_verified':True};ledger.setdefault('transitions',[]).append(trans);ledger['latest_transition_id']=tid;ledger['updated_at_utc']=trans['timestamp_utc'];ledger['required_closed_count']=sum(1 for x in rows if legally_closed(x));write_json(lp,ledger);eh=sha256_file(lp)
    invp=root/'evidence_inventory.json';inv=read_json(invp);once(inv.setdefault('off_w3_representative_profiler_attempts',[]),{'attempt_id':'OFF-W3-V1-MASTER','status':'VALIDATION_PASS','remote_raw_path':a.remote_attempt_root,'local_raw_path':str(s),'raw_file_set_sha256':raw,'routing_sha256':ROUTING_SHA,'actual_offloaded_bytes':4697620480,'wall_duration_ns':durations,'audit_v1_technical_failure_preserved':True});write_json(invp,inv)
    bp=root/'local_backup_manifest.json';b=read_json(bp);once(b.setdefault('phase7_attempt_backups',[]),{'attempt_id':'OFF-W3-V1-MASTER','remote_attempt':a.remote_attempt_root,'local_attempt':str(s),'status':'VERIFIED_RAW_VALIDATION_PASS_WITH_AUDIT_REPAIR_LINEAGE','file_set_sha256':raw});write_json(bp,b)
    rem=[x for x in rows if not legally_closed(x)];cond=[x['master_row_id'] for x in rem if x.get('trigger_state')=='PENDING'];blocked=[{'id':x['master_row_id'],'reason':x['blocker_or_failure']} for x in rem if x.get('blocker_or_failure')]
    write_json(root/'master_remaining_ledger.json',{'schema_version':'phase7-combined-master-remaining-ledger-v1','master_campaign_id':ledger['master_campaign_id'],'generated_from_execution_ledger_sha256':eh,'required_total':len(rows),'required_legally_closed':len(rows)-len(rem),'required_remaining_count':len(rem),'required_remaining_ids':[x['master_row_id'] for x in rem],'blocked_rows':blocked,'conditional_pending_count':len(cond),'conditional_pending_ids':cond,'phase7_status':ledger['status']})
    qpath=root/'master_ready_queue.json';q=read_json(qpath);q.update({'generated_from_execution_ledger_sha256':eh,'next_gpu_unit':'OFF-E-PR0','ready_gpu_units':['OFF-E-PR0'],'next_gate_action':'FREEZE_AND_RUN_OFF_E_PR0_COMPUTE_INTEGRATED_REPLAY','dispatch_guards':['MR2 read-only preflight clear','no foreign serving/GPU process at dispatch','OFF-W branch fully closed and locally backed up','OFF-E-PR0 independent compute-integrated replay contract frozen before dispatch','do not relabel replay as runtime-native dynamic expert residency','no filler workload','raw namespace independent']});write_json(qpath,q)
    name='MR11-OFF-W3-OFF-W3-V1-MASTER-PROMOTION.json';write_json(root/'reviews'/name,{'schema_version':'phase7-combined-master-off-w3-review-v1','reviewed_at_utc':trans['timestamp_utc'],'validation_state':'VALIDATION_PASS','pair_equivalence':'PASS','profiler_evidence':'PASS','actual_offloaded_bytes':4697620480,'wall_duration_ns':durations,'audit_repair_lineage':'PRESERVED_NO_GPU_RERUN','raw_file_set_sha256':raw,'next_ready_unit':'OFF-E-PR0'});write_json(root/'checkpoints'/name,{'schema_version':'phase7-combined-master-checkpoint-v1','checkpoint_id':tid,'timestamp_utc':trans['timestamp_utc'],'execution_ledger_sha256':eh,'remaining_ledger_sha256':sha256_file(root/'master_remaining_ledger.json'),'required_closed_count':len(rows)-len(rem),'required_remaining_count':len(rem),'next_ready_gpu_unit':'OFF-E-PR0','raw_file_set_sha256':raw})
    print(json.dumps({'execution_ledger_sha256':eh,'required_closed_count':len(rows)-len(rem),'required_remaining_count':len(rem),'next_ready_gpu_unit':'OFF-E-PR0','raw_file_set_sha256':raw,'wall_duration_ns':durations},indent=2,sort_keys=True));return 0
if __name__=='__main__':raise SystemExit(main())
