#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
from promote_combined_master_swap_k1_v5 import aggregate_hash,append_unique,evidence_file_hashes,legally_closed,now_utc,read_json,sha256_file,write_json
C='06e869ff5653a0c24e1bc890f55506d32d0b1b5e98324995048470b96bd54b63'
def once(rs,r):
 if not any(x.get('attempt_id')==r['attempt_id'] for x in rs):rs.append(r)
def main():
 p=argparse.ArgumentParser();p.add_argument('--master-root',type=Path,required=True);p.add_argument('--local-attempt-root',type=Path,required=True);p.add_argument('--remote-attempt-root',required=True);p.add_argument('--expected-aggregate-sha256',required=True);p.add_argument('--remote-suite-manifest-sha256',required=True);a=p.parse_args();s=a.local_attempt_root;raw=aggregate_hash(evidence_file_hashes(s));au=read_json(s/'off_e_pr2_suite_audit.json');d=au.get('prefetch_policy_replay',{})
 if sha256_file(s/'SUITE_SHA256SUMS')!=a.remote_suite_manifest_sha256 or raw!=a.expected_aggregate_sha256 or sha256_file(s/'off_e_pr2_contract.json')!=C or au.get('status')!='PASS' or au.get('final_output_routing_equivalence')!='PASS' or au.get('measured_policy_accounting_gate')!='PASS' or au.get('oracle_label_gate')!='PASS' or au.get('dependency_compute_gate')!='PASS':raise SystemExit('OFF-E-PR2 gate failed')
 root=a.master_root;lp=root/'master_execution_ledger.json';led=read_json(lp);prior=sha256_file(lp);rows=led['rows'];row=next(x for x in rows if x['master_row_id']=='OFF-E-PR2');tid='MR10-OFF-E-PR2-OFF-E-PR2-V1-MASTER-PROMOTION'
 for k,v in [('attempt_ids','OFF-E-PR2-V1-MASTER'),('remote_raw_paths',a.remote_attempt_root),('local_raw_paths',str(s)),('source_raw_sha256',raw)]:
  if v not in row.setdefault(k,[]):row[k].append(v)
 append_unique(row.setdefault('manifest_sha256',[]),[a.remote_suite_manifest_sha256,sha256_file(s/'off_e_pr2_suite_audit.json'),C]);summary={k:v['counts'] for k,v in d['measured_policies'].items()}
 row.update({'execution_state':'EXECUTION_COMPLETE','raw_state':'COMPLETE','backup_state':'VERIFIED','review_state':'REVIEW_WITH_LIMITATION','validation_state':'VALIDATION_PASS','adoption_state':'ADOPTED','blocker_or_failure':None,'claims_supported':append_unique(list(row.get('claims_supported',[])),['Actual-object static, causal-history and copy-aware causal prefetch replays preserved exact byte/category accounting and completed before actual FusedMoE compute.','Observed first-12 top-1 trace was all expert 1: static recorded 11 wasted; causal 11 useful; copy-aware one useful and ten duplicate cancellations.','Future oracle remained a separately labeled simulated upper bound with no executed H2D.']),'claims_forbidden':append_unique(list(row.get('claims_forbidden',[])),['Generalizing this single homogeneous trace to policy ranking, claiming speedup, treating zero late events as proof of no lateness, or relabeling oracle as measured.']),'contamination_flags':append_unique(list(row.get('contamination_flags',[])),['HOMOGENEOUS_FIRST12_DEMAND_TRACE_RETAINED','FUTURE_ORACLE_SIMULATED_ONLY']),'next_action':'Run frozen OFF-E-PR3 capacity anchors beginning with FIT 25%; held-out points remain untouched until their turn.','last_transition_record':tid})
 tr={'transition_id':tid,'timestamp_utc':now_utc(),'changed_rows':['OFF-E-PR2'],'reason':'Promote measured prefetch policy accounting and separately labeled oracle upper bound.','prior_ledger_sha256':prior,'attempt_id':'OFF-E-PR2-V1-MASTER','raw_file_set_sha256':raw,'policy_counts':summary,'remote_local_hashes_verified':True};led.setdefault('transitions',[]).append(tr);led['latest_transition_id']=tid;led['updated_at_utc']=tr['timestamp_utc'];led['required_closed_count']=sum(1 for x in rows if legally_closed(x));write_json(lp,led);eh=sha256_file(lp)
 ip=root/'evidence_inventory.json';inv=read_json(ip);once(inv.setdefault('off_e_pr2_attempts',[]),{'attempt_id':'OFF-E-PR2-V1-MASTER','status':'VALIDATION_PASS','remote_raw_path':a.remote_attempt_root,'local_raw_path':str(s),'raw_file_set_sha256':raw,'policy_counts':summary,'oracle_evidence_class':'SIMULATED_UPPER_BOUND'});write_json(ip,inv);bp=root/'local_backup_manifest.json';b=read_json(bp);once(b.setdefault('phase7_attempt_backups',[]),{'attempt_id':'OFF-E-PR2-V1-MASTER','remote_attempt':a.remote_attempt_root,'local_attempt':str(s),'status':'VERIFIED_RAW_VALIDATION_PASS','file_set_sha256':raw});write_json(bp,b)
 rem=[x for x in rows if not legally_closed(x)];cond=[x['master_row_id'] for x in rem if x.get('trigger_state')=='PENDING'];blocked=[{'id':x['master_row_id'],'reason':x['blocker_or_failure']} for x in rem if x.get('blocker_or_failure')];write_json(root/'master_remaining_ledger.json',{'schema_version':'phase7-combined-master-remaining-ledger-v1','master_campaign_id':led['master_campaign_id'],'generated_from_execution_ledger_sha256':eh,'required_total':len(rows),'required_legally_closed':len(rows)-len(rem),'required_remaining_count':len(rem),'required_remaining_ids':[x['master_row_id'] for x in rem],'blocked_rows':blocked,'conditional_pending_count':len(cond),'conditional_pending_ids':cond,'phase7_status':led['status']})
 nxt='OFF-E-PR3-CAP-025';qp=root/'master_ready_queue.json';q=read_json(qp);q.update({'generated_from_execution_ledger_sha256':eh,'next_gpu_unit':nxt,'ready_gpu_units':[nxt],'next_gate_action':'FREEZE_AND_RUN_OFF_E_PR3_CAPACITY_FIT_025','dispatch_guards':['MR2 read-only preflight clear','no foreign serving/GPU process at dispatch','OFF-E-PR0/PR1/PR2 validated and locally backed up','full capacity split and exact object count frozen','fit points before held-out interpretation','actual expert compute required','no filler workload','raw namespace independent']});write_json(qp,q)
 name='MR10-OFF-E-PR2-OFF-E-PR2-V1-MASTER-PROMOTION.json';write_json(root/'reviews'/name,{'schema_version':'phase7-combined-master-off-e-pr2-review-v1','reviewed_at_utc':tr['timestamp_utc'],'validation_state':'VALIDATION_PASS','policy_counts':summary,'oracle_label':'SIMULATED_UPPER_BOUND','raw_file_set_sha256':raw,'next_ready_unit':nxt});write_json(root/'checkpoints'/name,{'schema_version':'phase7-combined-master-checkpoint-v1','checkpoint_id':tid,'timestamp_utc':tr['timestamp_utc'],'execution_ledger_sha256':eh,'remaining_ledger_sha256':sha256_file(root/'master_remaining_ledger.json'),'required_closed_count':len(rows)-len(rem),'required_remaining_count':len(rem),'next_ready_gpu_unit':nxt,'raw_file_set_sha256':raw});print(json.dumps({'execution_ledger_sha256':eh,'required_closed_count':len(rows)-len(rem),'required_remaining_count':len(rem),'next_ready_gpu_unit':nxt,'raw_file_set_sha256':raw},indent=2));return 0
if __name__=='__main__':raise SystemExit(main())
