#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
from promote_combined_master_swap_k1_v5 import aggregate_hash,append_unique,evidence_file_hashes,legally_closed,now_utc,read_json,sha256_file,write_json
C='a7c7fe2587e29e0aa5d59b4a5e517f81f17b0dfa58863d98292baf07b172c91c'
def once(rs,r):
 if not any(x.get('attempt_id')==r['attempt_id'] for x in rs):rs.append(r)
def main():
 p=argparse.ArgumentParser();p.add_argument('--master-root',type=Path,required=True);p.add_argument('--local-attempt-root',type=Path,required=True);p.add_argument('--remote-attempt-root',required=True);p.add_argument('--expected-aggregate-sha256',required=True);p.add_argument('--remote-suite-manifest-sha256',required=True);a=p.parse_args();s=a.local_attempt_root;raw=aggregate_hash(evidence_file_hashes(s));au=read_json(s/'off_e_pr1_suite_audit.json');d=au.get('demand_load_replay',{})
 if sha256_file(s/'SUITE_SHA256SUMS')!=a.remote_suite_manifest_sha256 or raw!=a.expected_aggregate_sha256 or sha256_file(s/'off_e_pr1_contract.json')!=C or au.get('status')!='PASS' or au.get('final_output_routing_equivalence')!='PASS' or au.get('policy_byte_dependency_gate')!='PASS' or d.get('expert_object_bytes')!=352321536 or d.get('dependency_gate')!='PASS' or d.get('total_d2h_writeback_bytes')!=0:raise SystemExit('OFF-E-PR1 gate failed')
 root=a.master_root;lp=root/'master_execution_ledger.json';led=read_json(lp);prior=sha256_file(lp);rows=led['rows'];row=next(x for x in rows if x['master_row_id']=='OFF-E-PR1');tid='MR10-OFF-E-PR1-OFF-E-PR1-V1-MASTER-PROMOTION'
 for k,v in [('attempt_ids','OFF-E-PR1-V1-MASTER'),('remote_raw_paths',a.remote_attempt_root),('local_raw_paths',str(s)),('source_raw_sha256',raw)]:
  if v not in row.setdefault(k,[]):row[k].append(v)
 append_unique(row.setdefault('manifest_sha256',[]),[a.remote_suite_manifest_sha256,sha256_file(s/'off_e_pr1_suite_audit.json'),C])
 row.update({'execution_state':'EXECUTION_COMPLETE','raw_state':'COMPLETE','backup_state':'VERIFIED','review_state':'REVIEW_WITH_LIMITATION','validation_state':'VALIDATION_PASS','adoption_state':'ADOPTED','blocker_or_failure':None,'claims_supported':append_unique(list(row.get('claims_supported',[])),['Actual layer-0 expert objects were 352,321,536 bytes (w13+w2 BF16 slices) and actual H2D demand loads completed before FusedMoE compute.','Frozen capacity-2 sequence produced exact LRU 4-load/2-discard/1-hit and FIFO 3-load/1-discard/2-hit conservation with zero D2H writeback.','Clean/replay final output and routed-expert arrays were identical.']),'claims_forbidden':append_unique(list(row.get('claims_forbidden',[])),['Runtime-native expert residency, end-to-end speedup, CAL3 ranking or inclusion of host-snapshot setup D2H as demand traffic.']),'contamination_flags':append_unique(list(row.get('contamination_flags',[])),['LOGICAL_CACHE_POLICY_REPLAY_NOT_RUNTIME_NATIVE_RESIDENCY','HOST_SNAPSHOT_D2H_EXCLUDED_FROM_DEMAND_PATH']),'next_action':'Freeze OFF-E-PR2 static/causal/copy-aware prefetch replay and useful/wasted/late/cancelled accounting; oracle remains simulated upper bound only.','last_transition_record':tid})
 tr={'transition_id':tid,'timestamp_utc':now_utc(),'changed_rows':['OFF-E-PR1'],'reason':'Promote actual-object H2D, immutable-discard LRU/FIFO compute-integrated replay.','prior_ledger_sha256':prior,'attempt_id':'OFF-E-PR1-V1-MASTER','raw_file_set_sha256':raw,'remote_local_hashes_verified':True};led.setdefault('transitions',[]).append(tr);led['latest_transition_id']=tid;led['updated_at_utc']=tr['timestamp_utc'];led['required_closed_count']=sum(1 for x in rows if legally_closed(x));write_json(lp,led);eh=sha256_file(lp)
 ip=root/'evidence_inventory.json';inv=read_json(ip);once(inv.setdefault('off_e_pr1_attempts',[]),{'attempt_id':'OFF-E-PR1-V1-MASTER','status':'VALIDATION_PASS','remote_raw_path':a.remote_attempt_root,'local_raw_path':str(s),'raw_file_set_sha256':raw,'expert_object_bytes':352321536,'policies':{k:{z:v for z,v in d['policies'][k].items() if z in ('demand_load_count','hit_count','h2d_bytes')} for k in ('LRU','FIFO')}});write_json(ip,inv)
 bp=root/'local_backup_manifest.json';b=read_json(bp);once(b.setdefault('phase7_attempt_backups',[]),{'attempt_id':'OFF-E-PR1-V1-MASTER','remote_attempt':a.remote_attempt_root,'local_attempt':str(s),'status':'VERIFIED_RAW_VALIDATION_PASS','file_set_sha256':raw});write_json(bp,b)
 rem=[x for x in rows if not legally_closed(x)];cond=[x['master_row_id'] for x in rem if x.get('trigger_state')=='PENDING'];blocked=[{'id':x['master_row_id'],'reason':x['blocker_or_failure']} for x in rem if x.get('blocker_or_failure')];write_json(root/'master_remaining_ledger.json',{'schema_version':'phase7-combined-master-remaining-ledger-v1','master_campaign_id':led['master_campaign_id'],'generated_from_execution_ledger_sha256':eh,'required_total':len(rows),'required_legally_closed':len(rows)-len(rem),'required_remaining_count':len(rem),'required_remaining_ids':[x['master_row_id'] for x in rem],'blocked_rows':blocked,'conditional_pending_count':len(cond),'conditional_pending_ids':cond,'phase7_status':led['status']})
 qp=root/'master_ready_queue.json';q=read_json(qp);q.update({'generated_from_execution_ledger_sha256':eh,'next_gpu_unit':'OFF-E-PR2','ready_gpu_units':['OFF-E-PR2'],'next_gate_action':'FREEZE_AND_RUN_OFF_E_PR2_PREFETCH_POLICY_REPLAY','dispatch_guards':['MR2 read-only preflight clear','no foreign serving/GPU process at dispatch','OFF-E-PR0/PR1 validated and locally backed up','OFF-E-PR2 useful/wasted/late/cancelled definitions frozen','future oracle simulated upper bound only','actual expert compute required','no filler workload','raw namespace independent']});write_json(qp,q)
 name='MR10-OFF-E-PR1-OFF-E-PR1-V1-MASTER-PROMOTION.json';write_json(root/'reviews'/name,{'schema_version':'phase7-combined-master-off-e-pr1-review-v1','reviewed_at_utc':tr['timestamp_utc'],'validation_state':'VALIDATION_PASS','expert_object_bytes':352321536,'dependency_gate':'PASS','immutable_discard':'PASS','raw_file_set_sha256':raw,'next_ready_unit':'OFF-E-PR2'});write_json(root/'checkpoints'/name,{'schema_version':'phase7-combined-master-checkpoint-v1','checkpoint_id':tid,'timestamp_utc':tr['timestamp_utc'],'execution_ledger_sha256':eh,'remaining_ledger_sha256':sha256_file(root/'master_remaining_ledger.json'),'required_closed_count':len(rows)-len(rem),'required_remaining_count':len(rem),'next_ready_gpu_unit':'OFF-E-PR2','raw_file_set_sha256':raw});print(json.dumps({'execution_ledger_sha256':eh,'required_closed_count':len(rows)-len(rem),'required_remaining_count':len(rem),'next_ready_gpu_unit':'OFF-E-PR2','raw_file_set_sha256':raw},indent=2));return 0
if __name__=='__main__':raise SystemExit(main())
