#!/usr/bin/env python3
from __future__ import annotations
import argparse,json
from pathlib import Path
from promote_combined_master_swap_k1_v5 import aggregate_hash,append_unique,evidence_file_hashes,legally_closed,now_utc,read_json,sha256_file,write_json
CONTRACT='95fe4b815cd90a7e96824ca88e1f0d818f8c5bc383488fa3cfbf4613ac5a749f'
def once(rs,r):
 if not any(x.get('attempt_id')==r['attempt_id'] for x in rs):rs.append(r)
def main():
 p=argparse.ArgumentParser();p.add_argument('--master-root',type=Path,required=True);p.add_argument('--local-attempt-root',type=Path,required=True);p.add_argument('--remote-attempt-root',required=True);p.add_argument('--expected-aggregate-sha256',required=True);p.add_argument('--remote-suite-manifest-sha256',required=True);a=p.parse_args();s=a.local_attempt_root
 if sha256_file(s/'SUITE_SHA256SUMS')!=a.remote_suite_manifest_sha256:raise SystemExit('manifest mismatch')
 raw=aggregate_hash(evidence_file_hashes(s));audit=read_json(s/'off_e_pr0_suite_audit.json')
 if raw!=a.expected_aggregate_sha256 or sha256_file(s/'off_e_pr0_contract.json')!=CONTRACT or audit.get('status')!='PASS' or audit.get('final_output_and_routing_equivalence')!='PASS' or audit.get('timing_perturbation_gate')!='PASS' or audit.get('expert_replay_gate')!='PASS' or audit['expert_replay'].get('exact_equal') is not True or audit['expert_replay'].get('max_abs_error')!=0.0:raise SystemExit('OFF-E-PR0 gate failed')
 root=a.master_root;lp=root/'master_execution_ledger.json';led=read_json(lp);prior=sha256_file(lp);rows=led['rows'];row=next(x for x in rows if x['master_row_id']=='OFF-E-PR0');tid='MR10-OFF-E-PR0-OFF-E-PR0-V1-MASTER-PROMOTION'
 for k,v in [('attempt_ids','OFF-E-PR0-V1-MASTER'),('remote_raw_paths',a.remote_attempt_root),('local_raw_paths',str(s)),('source_raw_sha256',raw)]:
  if v not in row.setdefault(k,[]):row[k].append(v)
 append_unique(row.setdefault('manifest_sha256',[]),[a.remote_suite_manifest_sha256,sha256_file(s/'off_e_pr0_suite_audit.json'),CONTRACT,audit['expert_replay']['tensor_file_sha256']])
 row.update({'execution_state':'EXECUTION_COMPLETE','raw_state':'COMPLETE','backup_state':'VERIFIED','review_state':'REVIEW_WITH_LIMITATION','validation_state':'VALIDATION_PASS','adoption_state':'ADOPTED','blocker_or_failure':None,'claims_supported':append_unique(list(row.get('claims_supported',[])),['All-resident actual FusedMoE compute and same-input same-weight replay produced exact BF16 [256,4096] output with zero error and preserved final vLLM output/routing.','Trace-only instrumentation median request perturbation was 0.980771%, below the frozen 10% gate.','The replay preserves hidden/router readiness, top-2 decision, expert compute and completion lineage with zero H2D, writeback and eviction under all-resident semantics.']),'claims_forbidden':append_unique(list(row.get('claims_forbidden',[])),['Runtime-native dynamic expert offload, capacity-policy speedup, end-to-end CAL3 ranking or support-processor break-even from OFF-E-PR0.']),'contamination_flags':append_unique(list(row.get('contamination_flags',[])),['TRACE_DRIVEN_COMPUTE_INTEGRATED_REPLAY_NOT_RUNTIME_NATIVE_OFFLOAD']),'next_action':'Freeze OFF-E-PR1 demand load/immutable discard replay using actual captured expert compute and exact catalog bytes.','last_transition_record':tid})
 tr={'transition_id':tid,'timestamp_utc':now_utc(),'changed_rows':['OFF-E-PR0'],'reason':'Promote actual-compute all-resident replay fidelity with tensor equality, dependency lineage and perturbation gate.','prior_ledger_sha256':prior,'attempt_id':'OFF-E-PR0-V1-MASTER','raw_file_set_sha256':raw,'remote_local_hashes_verified':True};led.setdefault('transitions',[]).append(tr);led['latest_transition_id']=tid;led['updated_at_utc']=tr['timestamp_utc'];led['required_closed_count']=sum(1 for x in rows if legally_closed(x));write_json(lp,led);eh=sha256_file(lp)
 ip=root/'evidence_inventory.json';inv=read_json(ip);once(inv.setdefault('off_e_pr0_attempts',[]),{'attempt_id':'OFF-E-PR0-V1-MASTER','status':'VALIDATION_PASS','remote_raw_path':a.remote_attempt_root,'local_raw_path':str(s),'raw_file_set_sha256':raw,'tensor_file_sha256':audit['expert_replay']['tensor_file_sha256'],'timing_perturbation_relative_delta':audit['timing_perturbation_absolute_relative_delta']});write_json(ip,inv)
 bp=root/'local_backup_manifest.json';b=read_json(bp);once(b.setdefault('phase7_attempt_backups',[]),{'attempt_id':'OFF-E-PR0-V1-MASTER','remote_attempt':a.remote_attempt_root,'local_attempt':str(s),'status':'VERIFIED_RAW_VALIDATION_PASS','file_set_sha256':raw});write_json(bp,b)
 rem=[x for x in rows if not legally_closed(x)];cond=[x['master_row_id'] for x in rem if x.get('trigger_state')=='PENDING'];blocked=[{'id':x['master_row_id'],'reason':x['blocker_or_failure']} for x in rem if x.get('blocker_or_failure')];write_json(root/'master_remaining_ledger.json',{'schema_version':'phase7-combined-master-remaining-ledger-v1','master_campaign_id':led['master_campaign_id'],'generated_from_execution_ledger_sha256':eh,'required_total':len(rows),'required_legally_closed':len(rows)-len(rem),'required_remaining_count':len(rem),'required_remaining_ids':[x['master_row_id'] for x in rem],'blocked_rows':blocked,'conditional_pending_count':len(cond),'conditional_pending_ids':cond,'phase7_status':led['status']})
 qp=root/'master_ready_queue.json';q=read_json(qp);q.update({'generated_from_execution_ledger_sha256':eh,'next_gpu_unit':'OFF-E-PR1','ready_gpu_units':['OFF-E-PR1'],'next_gate_action':'FREEZE_AND_RUN_OFF_E_PR1_DEMAND_LOAD_EVICT_REPLAY','dispatch_guards':['MR2 read-only preflight clear','no foreign serving/GPU process at dispatch','OFF-E-PR0 actual-compute replay validated and locally backed up','OFF-E-PR1 exact catalog object bytes and immutable discard semantics frozen','actual expert compute required','no filler workload','raw namespace independent']});write_json(qp,q)
 name='MR10-OFF-E-PR0-OFF-E-PR0-V1-MASTER-PROMOTION.json';write_json(root/'reviews'/name,{'schema_version':'phase7-combined-master-off-e-pr0-review-v1','reviewed_at_utc':tr['timestamp_utc'],'validation_state':'VALIDATION_PASS','tensor_fidelity':'EXACT_EQUAL','timing_perturbation_relative_delta':audit['timing_perturbation_absolute_relative_delta'],'dependency_lineage':'PASS','raw_file_set_sha256':raw,'next_ready_unit':'OFF-E-PR1'});write_json(root/'checkpoints'/name,{'schema_version':'phase7-combined-master-checkpoint-v1','checkpoint_id':tid,'timestamp_utc':tr['timestamp_utc'],'execution_ledger_sha256':eh,'remaining_ledger_sha256':sha256_file(root/'master_remaining_ledger.json'),'required_closed_count':len(rows)-len(rem),'required_remaining_count':len(rem),'next_ready_gpu_unit':'OFF-E-PR1','raw_file_set_sha256':raw})
 print(json.dumps({'execution_ledger_sha256':eh,'required_closed_count':len(rows)-len(rem),'required_remaining_count':len(rem),'next_ready_gpu_unit':'OFF-E-PR1','raw_file_set_sha256':raw},indent=2));return 0
if __name__=='__main__':raise SystemExit(main())
